spring.application.name=Orbit

spring.config.import=application-secret.properties

server.port=80

spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
mybatis.mapper-locations=classpath:mappers/*-mapper.xml

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

spring.cloud.gcp.credentials.location=file:src/main/resources/GCP_Key.json
spring.cloud.gcp.bucket = orbit-private

jwt.expiration = 86400000